# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stollener Blog
email: stollener@gmail.com
author:
    name: Stollener
    # email: stollener@gmail.com
    # web: http://twitter.com/stollener
description: >- # this means to ignore newlines until "baseurl:"
  Stollener's Blog on coding, marketing, tech, advertising, and others.
  슈톨레너의 블로그입니다. 코딩, 마케팅, IT, 광고 등의 주제를 다룹니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stollener.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stollener
github_username:  stollener
g-analytics: UA-121414696-1

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-youtube
permalink: /blog/:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Theme tale
theme:      tale
# permalink:  /:year-:month-:day/:title
paginate:   5